# Setup
title:        The Coding Be[a|e]r
tagline:      Currently learning... Swift 
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Michal Wierzbinski
  url:        http://yourhomepage.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown